---
# tasks file for initialize-repository

    - name: Run 'restic init' command
      command: restic init
      environment:
         AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
         AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
         RESTIC_REPOSITORY: "s3:s3.ap-southeast-2.amazonaws.com/{{ bucket_name }}"
         RESTIC_PASSWORD: "emNlQ0EsSHQsQHdRa2F5fXt5cikwXSs8aE9Ce2MqYF0="