---
- hosts: "masters"
  remote_user: coinop
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
     - name: Get the token for joining the worker nodes
       shell: kubeadm token create  --print-join-command
       register: kubernetes_join_command

     - name: display token
       debug:
         msg: "{{ kubernetes_join_command.stdout }}"

     - name: Copy join command to local file.
       become: yes
       local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
