---
- hosts: "masters"
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
     - name: initialize the cluster
       shell: |
               kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_host }}
       when: inventory_hostname == "master"

     - name: After initializing the cluster
       shell: |
               mkdir -p $HOME/.kube
               sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
               sudo chown $(id -u):$(id -g) $HOME/.kube/config

     - name: Get the token for joining the worker nodes
       shell: kubeadm token create  --print-join-command
       register: kubernetes_join_command

     - name: display token
       debug:
         msg: "{{ kubernetes_join_command.stdout }}"

     - name: Copy join command to local file.
       become: yes
       local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
