---
- name: Manage SSH Authorized Keys
  hosts: all
  become: false

  vars_prompt:
    - name: new_ssh_key
      prompt: "Enter the new SSH key to add"
      private: false

    - name: old_ssh_key
      prompt: "Enter the SSH key you want to remove"
      private: false

  tasks:
    - name: Add new SSH key to authorized_keys
      ansible.posix.authorized_key:
        user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
        state: present
        key: "{{ new_ssh_key }}"


    - name: Remove specified SSH key from authorized_keys
      ansible.builtin.lineinfile:
        path: ~/.ssh/authorized_keys
        state: absent
        regexp: "{{ old_ssh_key | regex_escape() }}"